### ISSUE TITLE
Uses of <em> rather than <i> in endnotes?

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/giovanni-boccaccio_the-decameron_john-payne#2]
I'm a bit dubious about the use of `<em>` in the endnotes. I'm normally very keen to avoid bare `<i>` tags, but some of the instances, such as referencing names like:

```
<em>Pampinea</em>
<em>Fiammetta</em>
<em>Filomena</em>
```

or references to monastical hours:

```
<em>Matins</em>
<em>Prime</em>
<em>Tierce</em>
<em>Sexte</em>
<em>None</em>
<em>Vespers</em>
<em>Complines</em>
```

...don't seem to me in context to be semantically emphasised speech and might be better as just `<i>`. 

It's your call, just my two bits!

**Comment by vr8hub** [comment]
Right, I struggled with them as well. My logic, especially on the monastical hours, was that he doesn't italicize them anywhere else in the work, so he's not italicizing them because they're "foreign". And he was talking about everyone else's mis-translation of the terms. So maybe he was emphasizing what they really were.

Regardless of how, I think they _should_ be italicized. I'm happy to make them `<i>` instead.
